### ISSUE TITLE
Standard Prometheus alerts for v1

### ISSUE THREAD

**Issue by iancoffey** [deis/monitor#1]
We need to define:
- [ ] What alerts we need to create in the alert.rules for standard components.
- [ ] The syntax of how to implement them.
- [ ] Component down (router, publisher, etc..)
- [ ] Host memory consumption
- [ ] Increase in the 95 percentile of 5 minute load avg
- [ ] Low disk space (10% remaining, 5% remaining)
- [ ] Increase in the 95 percentile of response times for requests
- [ ] Above average errors rates from the router (# of 400s / # of requests)

**Comment by jchauncey** [comment]
* [ ] Component down (router, publisher, etc..)
* [ ] Host memory consumption
* [ ] Increase of 15 minute load avg (and probably 1 and 5 minute)
* [ ] Low disk space (10% remaining, 5% remaining)
* [ ] Increase in the 95 percentile of response times for requests
* [ ] Above average errors rates from the router (# of 400s / # of requests)
