### ISSUE TITLE
Write a prometheus exporter for nginx

### ISSUE THREAD

**Issue by jchauncey** [deis/monitor#10]
We need the ability to export metrics from the routers to prometheus. I  have 2 ideas on how to do this.

1) Build a daemon that attaches to the stdout/stderr of the process and parses the stream for all the relevant data. This would be ran within the router container.

2) Build a daemon that attaches to the log stream of the router container and parses the stream. This would be its own container.

(We could also do idea number 1 but have it parse the log files by using tee to redirect output to both stdout/stderr and log files)

**Comment by jchauncey** [comment]
If we wrote a self contained image that pull data from stdout/stderr then we could open source it. All it would need to do is take a regular expression for capture groups

**Comment by iancoffey** [comment]
We should also explore imaking a proper nginx module for providing a vhost/upstream level metrics endpoint. If it is technically possible, that might be the cleanest way to go long term and I bet something the community could really make use of. 

We might be able to crib some ideas from the approach they took here https://github.com/vozlt/nginx-module-vts

**Comment by jchauncey** [comment]
so i like the thought of using that module in the router image. However, prometheus has deprecated the ability to scrape json based endpoints. So we would need something that translates it into the prometheus format...

**Comment by jchauncey** [comment]
So @aledbf is awesome and has already added the `nginx-module-vts` to the router image. So I think having an http endpoint that uses the prometheus client to expose the metrics is our best way to go for this. I would just scrape the json endpoint and turn those into prometheus metrics using the golang lib.
