### ISSUE TITLE
Router dashboard doesn't show any data on kube-aws

### ISSUE THREAD

**Issue by krancour** [deis/monitor#100]
I tried this twice. With a fresh install for the workflow-rc1 or workflow-dev charts on a cluster in AWS, created via kube-aws (0.5.1), I don't get any data in the graphs on the router dashboard.

**Comment by jchauncey** [comment]
I think this was an issue with the old architecture. @krancour is this still a problem?

**Comment by krancour** [comment]
I forgot this was still open. I'm still using kube-aws and all is well with the dashboards. Closing.
