### ISSUE TITLE
Update telegraf to 1.0 release ASAP

### ISSUE THREAD

**Issue by jchauncey** [deis/monitor#102]
The telegraf 1.0 release isnt out yet but it has an important fix we need -

https://github.com/influxdata/telegraf/issues/1268

**Comment by sstarcher** [comment]
I'm running the beta of 1.0 telegraf atm against influxdb 0.13

**Comment by jchauncey** [comment]
So this should happen with the 2.1 release. However, it will not be their official beta release. We have built a 1 off binary that includes a plugin we have submitted to them that we are going to rely on for the 2.1 release.
