### ISSUE TITLE
Spike: Integrate Kapacitor

### ISSUE THREAD

**Issue by jchauncey** [deis/monitor#138]
After a conversation with the @influxdata team yesterday it is apparent that we should revisit integrating kapacitor into workflow. They stated that it is completely configurable with environment variables now (without the use of a config file) and it also exposes an API for driving the alert configuration. 

The influxdata team is also interested in helping us write some simple TICK scripts against the data we collect from k8s and workflow.

**Comment by bacongobbler** [comment]
let's keep this conversation going in #44 so we have one ticket to discuss integrating with kapacitor.
