### ISSUE TITLE
Deis Telegraf uses way too many Resources

### ISSUE THREAD

**Issue by felipejfc** [deis/monitor#159]
This is the usage of telegraf pods in my k8s cluster, I use AWS m4.xlarge instances as nodes

![image](https://cloud.githubusercontent.com/assets/285782/19832621/29b71b30-9e07-11e6-912f-c8f7216c090c.png)

![image](https://cloud.githubusercontent.com/assets/285782/19832623/371ba246-9e07-11e6-8b8e-27a909bc507a.png)

We have about 25 apps in Deis and about 42.000 RPM on it.

Is it normal that telegraf pods use this much resources?

**Comment by jchauncey** [comment]
What version of workflow are you using? We fixed a memory leak this last
release.

**Comment by bacongobbler** [comment]
ping @felipejfc, can you try upgrading to v2.8.0?

**Comment by bacongobbler** [comment]
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!
