### ISSUE TITLE
fluentd pod hogging memory after spike in traffic

### ISSUE THREAD

**Issue by gedimin45** [deis/monitor#166]
I deployed and app that output logs in a rapid pace (10s of message per second) and the fluentd pod memory consumption increased. Makes sense, but after I killed the app that was spamming logs, the memory consumption stays high. Seems like some messages just stay in memory.
I have also encountered this in the logs:

```
2016-12-14T14:03:29.277996730Z 2016-12-14 14:03:29 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `[]' for nil:NilClass" tag="kubernetes.var.log.containers.folksy-vacation-web-3441316637-w3jqs_folksy-vacation_POD-6998fb92734c2116c49ecff689f6314b7581c6931caf24717e90c0c8fc3da505.log"
2016-12-14T14:03:29.278460840Z   2016-12-14 14:03:29 +0000 [warn]: suppressed same stacktrace
```

**Comment by bacongobbler** [comment]
So the `undefined method '[]' for nil:NilClass` error from fluentd is a well-known unidentified upstream bug: https://github.com/fluent/fluentd/issues/1248

As for the memory consumption increase, given that fluentd and nsq needs to process all messages I'd imagine that'd stay under high memory consumption until the messages have been processed. Your throughput is simply slower than your input. Is there some form of enhancement you'd like to see from that?

**Comment by gedimin45** [comment]
The memory consumption did not go down one bit even after a day after the spike.
I think that when the `undefined method` error occurs, the object is not removed from memory but that is just a guess.
Would it be possible to predict a memory limit for the fluentd pod? Perhaps set a sane default in the chart?

**Comment by bacongobbler** [comment]
it is [commented out by default](https://github.com/deis/monitor/blob/master/charts/monitor/values.yaml#L5-L6) for clusters that want to run the monitoring stack with unlimited resources, but it is there. "sane defaults" differ from cluster to cluster, so there's no silver bullet.

**Comment by gedimin45** [comment]
Got it.
Pretty sure this is a bug in fluentd but I do not feel like debugging Ruby code that might have a bug under high load 😄 
Thanks for the suggestions!
