### ISSUE TITLE
Use upstream fluentd chart

### ISSUE THREAD

**Issue by mboersma** [deis/monitor#179]
Which might mean contributing to https://github.com/kubernetes/charts/pull/211 to help it meet Workflow's needs, if possible.

**Comment by kenden** [comment]
Related https://github.com/fluent/fluentd-kubernetes-daemonset/issues/8

**Comment by kenden** [comment]
@mboersma  There is now a chart at:
https://github.com/kubernetes/charts/tree/master/incubator/fluentd-cloudwatch

**Comment by bacongobbler** [comment]
Thanks for the heads up! We EOL’d Deis Workflow in September so we won’t get to doing this, but we are keeping this issue open for historical purposes. See https://deis.com/blog/2017/deis-workflow-final-release/

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/monitor#6
