### ISSUE TITLE
How to show Heapster metrics at Grafana?

### ISSUE THREAD

**Issue by pfeodrippe** [deis/monitor#189]
There is a way to configure heapster, InfluxDB and Grafana in a Kubernetes cluster show [here](https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb). How could I achieve this from the standalone heapster deploy using the already present InfluxDB and Grafana pods?

**Comment by jchauncey** [comment]
Not sure I fully understand. You already have a workflow install with influx and grafana and you want to send heapster metrics to that influx instance?

**Comment by pfeodrippe** [comment]
Yes, exactly. I've saw one of the posts at the deis blog talking about these three together, maybe setting the sink property at the heapster yaml config?

**Comment by jchauncey** [comment]
Yeah you could set the sink config for heapster and it would send those metrics to the influxdb instance installed by workflow.

**Comment by pfeodrippe** [comment]
@jchauncey Thanks!

**Comment by bacongobbler** [comment]
closing the question as answered, please feel free to re-open otherwise.
