### ISSUE TITLE
Proposal: containerize the development environment

### ISSUE THREAD

**Issue by krancour** [deis/monitor#24]
This is to lower the barrier to entry for hacking on Deis while also standardizing the development environment for all contributors.

**Comment by iancoffey** [comment]
Genesis: https://github.com/deis/deis/issues/4351#issuecomment-157456507

**Comment by ghost** [comment]
Hi @krancour. What is the best way to proceed on a potential PR for this? Should I branch from the branch `v2` of the `deis` repository?

Got a little confused. So any pointer to docs, or conversations will be fully appreciated. I'm currently working on a way to containerize the dev env.

**Comment by iancoffey** [comment]
@hermanjunge for the Monitor project specifically, it is probably too early to containerize this dev environment because the base functionality isnt all there quite yet.

We're cooking that up right now, later this week I will update this issue. Cheers!

**Comment by ghost** [comment]
I see. Thanks for the heads up!
