### ISSUE TITLE
Volume for persistent storage.

### ISSUE THREAD

**Issue by iancoffey** [deis/monitor#6]
We need a persistent volume for Prometheus storage.

**Comment by jchauncey** [comment]
The crappy thing here is making sure its always scheduled on the same node. I'm not sure how that happens with k8s

**Comment by iancoffey** [comment]
Sorry I def need to add v1/v2 labels on all these. FWIW, all of these initial issues are around finishing the v1 stuff (except https://github.com/deis/monitor/issues/9). So in that case, we'll have to find how best to leverage either a ceph backed volume or an s3 bucket for stateless.
