### ISSUE TITLE
Handle influx wal logs

### ISSUE THREAD

**Issue by jchauncey** [deis/monitor#70]
We should write the wal logs for influx into cluster storage. Right now I dont think influx handles s3 backends but it would be nice if it did so we could mimic what postgres does.

**Comment by arschles** [comment]
@jchauncey can you expand on the description here? Do you want to stream the wal to S3?

**Comment by bacongobbler** [comment]
ping

**Comment by jchauncey** [comment]
I think this issue should be closed. We state clearly that you should host influx off cluster just like postgres so streaming the transaction logs is really an overhead that doesn't make much sense.
