### ISSUE TITLE
Telegraf Tag support for cloud providers

### ISSUE THREAD

**Issue by sstarcher** [deis/monitor#78]
Would their be any interest in adding cloud specific tags to the telegraf data?  I currently add AWS instance_id to the global_tags field of telegraf.

**Comment by jchauncey** [comment]
yeah I wasnt sure how I wanted to accomplish this with pulling the data into the toml file. If you have any suggestions Id be welcome to take a look

**Comment by sstarcher** [comment]
How about relying on the pod definition to pass in the data and using helm to generate the template.

So pass in an environment variable to telegraf -e GLOBAL_TAGS='KEY:VALUE,KEY:VALUE"

**Comment by jchauncey** [comment]
closed via #79
