### ISSUE TITLE
Implement permanent storage for Grafana

### ISSUE THREAD

**Issue by jchauncey** [deis/monitor#92]
The grafana pod should be able to restore data from a persistent storage option.

**Comment by felipejfc** [comment]
+1

My grafana pod sometimes restarts and then I lose all the dashboards on it :/

**Comment by jchauncey** [comment]
For a work around you can always export the json after you have made your changes. It is also possible to take that json and add it [here](https://github.com/deis/monitor/tree/master/grafana/rootfs/usr/share/grafana/api/dashboards) and rebuild the image and deploy it so your dashboards show up when the container starts.

**Comment by jgmize** [comment]
see https://github.com/kubernetes/charts/tree/master/stable/grafana for implementation.

**Comment by vdice** [comment]
On-cluster storage option (via pv,pvc) implemented in https://github.com/deis/monitor/pull/169
