### ISSUE TITLE
Implement permanent storage for Influx

### ISSUE THREAD

**Issue by jchauncey** [deis/monitor#93]
The influx pod should be able to restore data from a persistent storage option.

**Comment by sstarcher** [comment]
For this and #92 do you an idea of the prefered implementation?  I'm considering doing this for my AWS setup, but would be interested in making it generic.  It would be nice if Helm had built in support for storage.

**Comment by jchauncey** [comment]
So right now I dont think influx supports directly writing to an s3 compatible api (at least I haven't seen it in the docs). That would be the best solution because then I can provide a solution like we do for `deis/database` which is more agnostic to the storage backend.

**Comment by sstarcher** [comment]
@jchauncey got ya.  My interest is certainly more in specific Kubernetes support for AWS and GCE via volume attachment.

**Comment by jchauncey** [comment]
I think if we had a solution that worked for aws and gce that would be a great start

**Comment by jgmize** [comment]
See https://github.com/kubernetes/charts/tree/master/stable/influxdb

**Comment by vdice** [comment]
On-cluster storage option (via pv,pvc) implemented in https://github.com/deis/monitor/pull/169
